name: Continuous Integration
on: push

jobs:
  ci:
    name: CI
    uses: acidicoala/KoalaBox/.github/workflows/build-and-package.yml@84d86aecbfc185e786a4fc162c7d17ec7e6ac365
    permissions:
      contents: write
    with:
      arch: '[ 32, 64 ]'
      config: Release
      modules: >-
        [
          "userenv",
          "audioses",
          "d3d9",
          "d3d10",
          "d3d11",
          "dinput8",
          "dwmapi",
          "dxgi",
          "glu32",
          "hid",
          "iphlpapi",
          "msasn1",
          "msimg32",
          "mswsock",
          "opengl32",
          "profapi",
          "propsys",
          "textshaping",
          "version",
          "winhttp",
          "wldp",
          "winmm",
          "xinput9_1_0"
        ]

      zip_command: >
        cp res/Koaloader.config.json artifacts/Koaloader.config.json &&
        cd artifacts &&
        zip ../$ZIP_NAME ./* -r
